### ISSUE TITLE
No Facebook auth option

### ISSUE THREAD

**Issue by Manifold0** [IAmPicard/STTCrewMobile#1]
I'm in the process of working my way through DB customer service to get my Facebook account turned into a real account so I can login to the app, but for now I'm locked out because my account was created via Facebook and therefore DB has no email and password on file for me.

It seems like this is a bit of an oversight on DB's part, but a Facebook auth option in the app would let Facebook users login without all of the DB overhead.

**Comment by IAmPicard** [comment]
Added Facebook login support with commit 00cab98edf4692a7e45b7f49a8fa519ff197485b . I'll try to build a new release with it or if you have a build environment already set up, just sync that and rebuild.

**Comment by IAmPicard** [comment]
Released a new version that includes support for Facebook login. [Check it out here](https://github.com/IAmPicard/STTCrewMobile/releases/tag/v0.0.2). Let me know if this works for you.

**Comment by Manifold0** [comment]
Seems to be working. I'll fiddle with it a bit to be sure.
